// create
POST http://localhost:3001/api/importInvoice/add
Content-Type: application/json

{
  "GiaSPN": "200000",
  "MaKhoHang": "1",
  "MaSP": "SP001",
  "NgayLapHDN": "2021-10-3",
  "SoLuongNhap": "25",
}

###
GET http://localhost:3001/api/carts/sumproduct/Username=B1809248


###
PUT http://localhost:3001/api/cart/update
Content-Type: application/json

{
  "Username": "B1809248",
  "MaSP": "SP003",
  "SLSP": 100
}

