// create
POST http://localhost:3001/api/exportInvoice/add
Content-Type: application/json

 {

      "NgayLapHDX": "10-08-2000",
      "TrangThaiHD": 0, 
      "TinhTrangHD": 0,
      "MaKH": "1",
      "MaKhoHang": "1",
    }

###

GET http://localhost:3001/api/chitiethoadonxuat/SumOrder/MaHDX=43
